name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm ci --no-progress --legacy-peer-deps
      timeout-minutes: 10  

    - name: Restart Angular App
      run: pm2 restart core-edge

